---
- name: Install apache server
  hosts: web
  become: yes
  
  tasks:
  - name: latest apache version installed
    apt:
      name: apache2
      state: latest

  - name: check apache2.service state
    service:
      name: apache2.service
      enabled: yes
      state: started

