---
- name: Install vsftpd on ftpservers
  hosts: all
  become: true

  tasks:
  - name: Install FTP server when host in ftpserver group
    apt:
      name: vsftpd
      state: latest
    when: inventory_hostname in groups["ftpserver"]